version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      determinatesystems-actions:
        patterns:
          - 'DeterminateSystems*'
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: 'monthly'
