[package]
name = "zsh-history-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.5"
nom = "7.1.0"

[dev-dependencies]
pretty_assertions = "1.0.0"
rstest = "0.12.0"
rstest_reuse = "0.1.3"
