name: ❄️
on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/ci.yml'
      - '**.nix'
      - 'flake.*'
      - '**.rs'
      - 'Cargo.*'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - '**.nix'
      - 'flake.*'
      - '**.rs'
      - 'Cargo.*'
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'
  workflow_dispatch:

jobs:
  nix:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@da36cb69b1c3247ad7a1f931ebfd954a1105ef14 # v14
      - run: nix develop --command echo 'This step should be done before any other "nix develop" steps because of measuring Nix build time'
      - run: nix flake check
      - run: nix flake show
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@da36cb69b1c3247ad7a1f931ebfd954a1105ef14 # v14
      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2
        with:
          # flack.lock for https://github.com/kachick/dprint-plugin-kdl/pull/39#issuecomment-2396115803
          # Adding flake.nix to consider the environment values
          key: additional-${{ hashFiles('flake.*') }}
      - run: nix develop --command cargo build
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@da36cb69b1c3247ad7a1f931ebfd954a1105ef14 # v14
      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2
        with:
          # flack.lock for https://github.com/kachick/dprint-plugin-kdl/pull/39#issuecomment-2396115803
          # Adding flake.nix to consider the environment values
          key: additional-${{ hashFiles('flake.*') }}
      - run: nix develop --command cargo test --locked --all-features
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@da36cb69b1c3247ad7a1f931ebfd954a1105ef14 # v14
      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2
        with:
          # flack.lock for https://github.com/kachick/dprint-plugin-kdl/pull/39#issuecomment-2396115803
          # Adding flake.nix to consider the environment values
          key: additional-${{ hashFiles('flake.*') }}
      - run: nix develop --command cargo fmt --check
      - run: nix develop --command cargo clippy
