name: ❄️
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci.yml'
      - '**.nix'
      - 'flake.*'
      - '**.rs'
      - 'Cargo.*'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - '**.nix'
      - 'flake.*'
      - '**.rs'
      - 'Cargo.*'
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@da36cb69b1c3247ad7a1f931ebfd954a1105ef14 # v14
      - uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b # v8
      - run: nix develop --command echo 'This step should be done before any other "nix develop" steps because of measuring Nix build time'
      - run: nix flake check
      - run: nix flake show
      - run: nix develop --command cargo test --locked --all-features
      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2
      - run: nix develop --command cargo build
